
project_id = "fxelhfwaoizqyecikscu"

[functions]
  [functions.brreg]
    verify_jwt = true
  [functions.pdf-converter]
    verify_jwt = true
  [functions.pdf-text-extractor]
    verify_jwt = true
  [functions.enhanced-pdf-text-extractor]
    verify_jwt = true
  [functions.document-ai-analyzer]
    verify_jwt = true
  [functions.ai-transaction-analysis]
    verify_jwt = true
  [functions.revy-ai-chat]
    verify_jwt = false
  [functions.syncKunngjoring]
    verify_jwt = false
  [functions.text-to-speech]
    verify_jwt = true
  [functions.voice-to-text]
    verify_jwt = true
  [functions.knowledge-search]
    verify_jwt = false
  [functions.generate-embeddings]
    verify_jwt = true
  [functions.calculate-formula]
    verify_jwt = true
  [functions.group-messages]
    verify_jwt = true
  [functions.import-payroll]
    verify_jwt = true
  [functions.calculate-population-from-accounts]
    verify_jwt = true
  [functions.shareholders-import]
    verify_jwt = true
  [functions.shareholders-search]
    verify_jwt = true
  [functions.ownership-graph]
    verify_jwt = true
  [functions.shareholders-import-start]
    verify_jwt = true
  [functions.shareholders-ingest-batch]
    verify_jwt = true
  [functions.shareholders-import-finish]
    verify_jwt = true
  [functions.revy-multi-agent]
    verify_jwt = true
  [functions.revy-role-test]
    verify_jwt = true
  [functions.revy-model-test]
    verify_jwt = true
  [functions.shareholders-import-finish-batch]
    verify_jwt = true
  [functions.shareholders-import-recover]
    verify_jwt = true
  [functions.shareholders-bulk-import]
    verify_jwt = true
  [functions.shareholders-batch-processor]
    verify_jwt = true
  [functions.shareholders-optimized-import]
    verify_jwt = true
  [functions.shareholders-unified-import]
    verify_jwt = true
  [functions.shareholders-status]
    verify_jwt = true
