
project_id = "fxelhfwaoizqyecikscu"

[functions]
  [functions.brreg]
    verify_jwt = true
  [functions.pdf-converter]
    verify_jwt = true
  [functions.pdf-text-extractor]
    verify_jwt = true
  [functions.enhanced-pdf-text-extractor]
    verify_jwt = true
  [functions.document-ai-analyzer]
    verify_jwt = true
  [functions.revy-ai-chat]
    verify_jwt = false
  [functions.syncKunngjoring]
    verify_jwt = false
  [functions.text-to-speech]
    verify_jwt = true
  [functions.voice-to-text]
    verify_jwt = true
  [functions.knowledge-search]
    verify_jwt = false
  [functions.generate-embeddings]
    verify_jwt = true
  [functions.calculate-formula]
    verify_jwt = true
  [functions.group-messages]
    verify_jwt = true
  [functions.import-payroll]
    verify_jwt = true
