
import { Client } from '@/types/revio';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Nordheim AS',
    company_name: 'Nordheim Konsern',
    org_number: '912345678',
    phase: 'planning',
    progress: 65,
    department: 'Oslo',
    contact_person: 'Mats Hansen',
    chair: 'Ola Nordmann',
    ceo: 'Erik Hansen',
    industry: 'Eiendom',
    registration_date: '2010-05-10',
    address: 'Storgata 1',
    postal_code: '0123',
    city: 'Oslo',
    riskAreas: [
      { name: 'Inntekter', risk: 'medium' },
      { name: 'Kostnader', risk: 'low' },
      { name: 'Anleggsmidler', risk: 'high' }
    ],
    documents: [
      { type: 'shareholder_report', status: 'pending', dueDate: '2025-05-15' },
      { type: 'tax_return', status: 'pending', dueDate: '2025-06-30' },
      { type: 'annual_report', status: 'pending', dueDate: '2025-07-31' }
    ],
    email: '',
    phone: '',
    bank_account: '',
    notes: '',
    org_form_code: 'AS',
    org_form_description: 'Aksjeselskap',
    homepage: '',
    status: 'ACTIVE',
    nace_code: '',
    nace_description: '',
    municipality_code: '',
    municipality_name: '',
    equity_capital: 0,
    share_capital: 0,
    accounting_system: 'Visma Business',
    previous_auditor: 'Ernst & Young',
    audit_fee: 125000,
    year_end_date: '2024-12-31',
    board_meetings_per_year: 4,
    internal_controls: 'Godt etablert',
    risk_assessment: 'Middels risiko',
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-01-01T00:00:00Z',
    roles: []
  },
  {
    id: '2',
    name: 'Sørland Byggverk AS',
    company_name: 'Sørland Gruppe',
    org_number: '921234567',
    phase: 'execution',
    progress: 40,
    department: 'Kristiansand',
    contact_person: 'Julie Nilsen',
    chair: 'Per Andersen',
    ceo: 'Lisa Olsen',
    industry: 'Bygg og anlegg',
    registration_date: '2015-03-15',
    address: 'Havnegata 5',
    postal_code: '4630',
    city: 'Kristiansand',
    riskAreas: [
      { name: 'Inntekter', risk: 'low' },
      { name: 'Kostnader', risk: 'medium' },
      { name: 'Anleggsmidler', risk: 'low' }
    ],
    documents: [
      { type: 'shareholder_report', status: 'pending', dueDate: '2025-05-15' },
      { type: 'tax_return', status: 'pending', dueDate: '2025-06-30' },
      { type: 'annual_report', status: 'pending', dueDate: '2025-07-31' }
    ],
    email: '',
    phone: '',
    bank_account: '',
    notes: '',
    org_form_code: 'AS',
    org_form_description: 'Aksjeselskap',
    homepage: '',
    status: 'ACTIVE',
    nace_code: '',
    nace_description: '',
    municipality_code: '',
    municipality_name: '',
    equity_capital: 0,
    share_capital: 0,
    accounting_system: 'PowerOffice',
    previous_auditor: 'PwC',
    audit_fee: 85000,
    year_end_date: '2024-12-31',
    board_meetings_per_year: 6,
    internal_controls: 'Under utvikling',
    risk_assessment: 'Lav risiko',
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-01-01T00:00:00Z',
    roles: []
  }
];
