
import { Client } from '@/types/revio';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Acme Corporation AS',
    company_name: 'Acme Corporation AS',
    org_number: '123456789',
    industry: 'Technology',
    phase: 'planning',
    progress: 65,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T14:30:00Z',
    department: 'Oslo',
    contact_person: 'John Doe',
    chair: 'Jane Smith',
    ceo: 'Bob Johnson',
    address: 'Storgata 1',
    postal_code: '0001',
    city: 'Oslo',
    email: 'contact@acme.no',
    phone: '+47 12345678',
    bank_account: '12345678901',
    notes: 'Important client - high priority',
    org_form_code: 'AS',
    org_form_description: 'Aksjeselskap',
    homepage: 'https://acme.no',
    status: 'ACTIVE',
    nace_code: '62.01',
    nace_description: 'Programmering',
    municipality_code: '0301',
    municipality_name: 'Oslo',
    equity_capital: 1000000,
    share_capital: 500000,
    accounting_system: 'Visma',
    previous_auditor: 'KPMG',
    year_end_date: '2024-12-31',
    internal_controls: 'Good',
    risk_assessment: 'Medium',
    audit_fee: 150000,
    board_meetings_per_year: 4,
    riskAreas: [
      { name: 'Revenue Recognition', risk: 'medium' },
      { name: 'Inventory Valuation', risk: 'low' }
    ],
    documents: [
      { type: 'Financial Statements', status: 'pending', dueDate: '2024-03-31' },
      { type: 'Tax Returns', status: 'completed', dueDate: '2024-02-28' }
    ],
    roles: [],
    announcements: []
  },
  {
    id: '2',
    name: 'Beta Industries AS',
    company_name: 'Beta Industries AS',
    org_number: '987654321',
    industry: 'Manufacturing',
    phase: 'execution',
    progress: 40,
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-25T16:45:00Z',
    department: 'Bergen',
    contact_person: 'Alice Brown',
    chair: 'Charlie Wilson',
    ceo: 'Diana Green',
    address: 'Industrigata 15',
    postal_code: '5001',
    city: 'Bergen',
    email: 'info@beta.no',
    phone: '+47 87654321',
    bank_account: '98765432109',
    notes: 'Manufacturing client with complex inventory',
    org_form_code: 'AS',
    org_form_description: 'Aksjeselskap',
    homepage: 'https://beta.no',
    status: 'ACTIVE',
    nace_code: '25.11',
    nace_description: 'Produksjon av metallkonstruksjoner',
    municipality_code: '4601',
    municipality_name: 'Bergen',
    equity_capital: 2000000,
    share_capital: 1000000,
    accounting_system: 'SAP',
    previous_auditor: 'EY',
    year_end_date: '2024-12-31',
    internal_controls: 'Excellent',
    risk_assessment: 'Low',
    audit_fee: 200000,
    board_meetings_per_year: 6,
    riskAreas: [
      { name: 'Inventory Management', risk: 'high' },
      { name: 'Fixed Assets', risk: 'medium' }
    ],
    documents: [
      { type: 'Management Letter', status: 'draft', dueDate: '2024-04-15' },
      { type: 'Audit Report', status: 'pending', dueDate: '2024-04-30' }
    ],
    roles: [],
    announcements: []
  }
];
