-- Update standard_accounts table to use accounting line numbers (regnskapslinjenummer)
-- First, clear existing data
DELETE FROM public.standard_accounts;

-- Insert the correct accounting line numbers and names
INSERT INTO public.standard_accounts (standard_number, standard_name, account_type, category, analysis_group) VALUES
('10', 'Salgsinntekt', 'revenue', 'Driftsinntekter', 'income_statement'),
('15', 'Annen driftsinntekt', 'revenue', 'Driftsinntekter', 'income_statement'),
('19', 'Sum driftsinntekter', 'revenue', 'Driftsinntekter', 'income_statement'),
('20', 'Varekostnad', 'expense', 'Driftskostnader', 'income_statement'),
('30', 'End. beh. varer u. tilv. og ferdigvarer', 'expense', 'Driftskostnader', 'income_statement'),
('40', 'Lønnskostnad', 'expense', 'Driftskostnader', 'income_statement'),
('50', 'Avskrivning', 'expense', 'Driftskostnader', 'income_statement'),
('60', 'Nedskrivning', 'expense', 'Driftskostnader', 'income_statement'),
('70', 'Annen driftskostnad', 'expense', 'Driftskostnader', 'income_statement'),
('79', 'Sum driftskostnader', 'expense', 'Driftskostnader', 'income_statement'),
('80', 'Driftsresultat', 'revenue', 'Resultat', 'income_statement'),
('90', 'Inntekt på investering i datterselskap', 'revenue', 'Finansposter', 'income_statement'),
('95', 'Inntekt på investering i annet foretak i samme konsern', 'revenue', 'Finansposter', 'income_statement'),
('100', 'Inntekt på investering i tilknyttet selskap', 'revenue', 'Finansposter', 'income_statement'),
('105', 'Renteinntekt fra foretak i samme konsern', 'revenue', 'Finansposter', 'income_statement'),
('106', 'Renteinntekt fra tilknyttet selskap', 'revenue', 'Finansposter', 'income_statement'),
('110', 'Annen renteinntekt', 'revenue', 'Finansposter', 'income_statement'),
('115', 'Annen finansinntekt', 'revenue', 'Finansposter', 'income_statement'),
('120', 'Verdiøkning markedsbaserte omløpsmidler', 'revenue', 'Finansposter', 'income_statement'),
('125', 'Verdireduksjon markedsbaserte omløpsmidler', 'expense', 'Finansposter', 'income_statement'),
('130', 'Nedskrivning av finansielle eiendeler', 'expense', 'Finansposter', 'income_statement'),
('135', 'Nedskrivning av andre finansielle anleggsmidler', 'expense', 'Finansposter', 'income_statement'),
('140', 'Rentekostnad til foretak i samme konsern', 'expense', 'Finansposter', 'income_statement'),
('141', 'Rentekostnad til tilknyttet selskap', 'expense', 'Finansposter', 'income_statement'),
('145', 'Annen rentekostnad', 'expense', 'Finansposter', 'income_statement'),
('150', 'Annen finanskostnad', 'expense', 'Finansposter', 'income_statement'),
('155', 'Resultat av finansposter', 'revenue', 'Finansposter', 'income_statement'),
('160', 'Resultat før skattekostnad', 'revenue', 'Resultat', 'income_statement'),
('165', 'Skattekostnad på resultat', 'expense', 'Resultat', 'income_statement'),
('280', 'Årsresultat', 'revenue', 'Resultat', 'income_statement'),
('285', 'Avsatt til dekning av tidligere udekket tap', 'equity', 'Egenkapitaldisponering', 'equity'),
('290', 'Avsatt til fond for vurderingsforskjeller', 'equity', 'Egenkapitaldisponering', 'equity'),
('295', 'Avsatt til utbytte', 'equity', 'Egenkapitaldisponering', 'equity'),
('296', 'Tilleggsutbytte', 'equity', 'Egenkapitaldisponering', 'equity'),
('297', 'Ekstraordinært utbytte', 'equity', 'Egenkapitaldisponering', 'equity'),
('300', 'Mottatt konsernbidrag', 'revenue', 'Egenkapitaldisponering', 'equity'),
('305', 'Avsatt konsernbidrag', 'expense', 'Egenkapitaldisponering', 'equity'),
('320', 'Avsatt til annen Egenkapital', 'equity', 'Egenkapitaldisponering', 'equity'),
('325', 'Overført fra fond for vurderignsforskjeller', 'equity', 'Egenkapitaldisponering', 'equity'),
('330', 'Overført til udekket tap', 'equity', 'Egenkapitaldisponering', 'equity'),
('335', 'Overført fra annen egenkapital', 'equity', 'Egenkapitaldisponering', 'equity'),
('350', 'Sum overføringer', 'equity', 'Egenkapitaldisponering', 'equity'),
('510', 'Utvikling', 'asset', 'Immatterielle eiendeler', 'balance_sheet'),
('515', 'Konsesjoner, patenter o.l.', 'asset', 'Immatterielle eiendeler', 'balance_sheet'),
('520', 'Utsatt skattefordel', 'asset', 'Immatterielle eiendeler', 'balance_sheet'),
('525', 'Goodwill', 'asset', 'Immatterielle eiendeler', 'balance_sheet'),
('530', 'Sum immatterielle eiendeler', 'asset', 'Immatterielle eiendeler', 'balance_sheet'),
('535', 'Tomter, bygninger o.a. fast eiendom', 'asset', 'Varige driftsmidler', 'balance_sheet'),
('540', 'Maskiner og anlegg', 'asset', 'Varige driftsmidler', 'balance_sheet'),
('545', 'Skip og flytende installasjoner', 'asset', 'Varige driftsmidler', 'balance_sheet'),
('550', 'Driftsløsøre, inventar o.a. utstyr', 'asset', 'Varige driftsmidler', 'balance_sheet'),
('555', 'Sum varige driftsmidler', 'asset', 'Varige driftsmidler', 'balance_sheet'),
('560', 'Investering i datterselskap', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('565', 'Investering i annet foretak i samme konsern', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('570', 'Lån til foretak i samme konsern', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('575', 'Investeringer i tilknyttet selskap', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('580', 'Lån til tilknyttet selskap og felles kontrollert virksomhet', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('585', 'Investeringer i aksjer og andeler', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('590', 'Obligasjoner', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('591', 'Andre langsiktige fordringer', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('595', 'Sum finansielle anleggsmidler', 'asset', 'Finansielle anleggsmidler', 'balance_sheet'),
('600', 'Sum anleggsmidler', 'asset', 'Anleggsmidler', 'balance_sheet'),
('605', 'Lager av varer og annen beholdning', 'asset', 'Omløpsmidler', 'balance_sheet'),
('610', 'Kundefordringer', 'asset', 'Omløpsmidler', 'balance_sheet'),
('611', 'Kundefordringer konsern', 'asset', 'Omløpsmidler', 'balance_sheet'),
('615', 'Andre kortsiktige fordringer', 'asset', 'Omløpsmidler', 'balance_sheet'),
('618', 'Konsernfordringer', 'asset', 'Omløpsmidler', 'balance_sheet'),
('620', 'Krav på innbetaling av aksjekapital', 'asset', 'Omløpsmidler', 'balance_sheet'),
('625', 'Sum fordringer', 'asset', 'Omløpsmidler', 'balance_sheet'),
('630', 'Aksjer og andeler i foretak i samme konsern', 'asset', 'Investeringer', 'balance_sheet'),
('635', 'Markedsbaserte aksjer', 'asset', 'Investeringer', 'balance_sheet'),
('640', 'Markedsbaserte obligasjoner', 'asset', 'Investeringer', 'balance_sheet'),
('645', 'Andre markedsbaserte finansielle instrumenter', 'asset', 'Investeringer', 'balance_sheet'),
('650', 'Andre finansielle instrumenter', 'asset', 'Investeringer', 'balance_sheet'),
('654', 'Sum investeringer', 'asset', 'Investeringer', 'balance_sheet'),
('655', 'Bankinnskudd, kontanter o.l.', 'asset', 'Omløpsmidler', 'balance_sheet'),
('660', 'Sum omløpsmidler', 'asset', 'Omløpsmidler', 'balance_sheet'),
('665', 'Sum eiendeler', 'asset', 'Eiendeler', 'balance_sheet'),
('670', 'Aksjekapital', 'equity', 'Innskutt egenkapital', 'balance_sheet'),
('675', 'Egne aksjer', 'equity', 'Innskutt egenkapital', 'balance_sheet'),
('680', 'Overkurs', 'equity', 'Innskutt egenkapital', 'balance_sheet'),
('681', 'Annen innskutt egenkapital', 'equity', 'Innskutt egenkapital', 'balance_sheet'),
('685', 'Sum innskutt egenkapital', 'equity', 'Innskutt egenkapital', 'balance_sheet'),
('690', 'Fond for vurderingsforksjeller', 'equity', 'Opptjent egenkapital', 'balance_sheet'),
('695', 'Annen egenkapital', 'equity', 'Opptjent egenkapital', 'balance_sheet'),
('700', 'Udekket tap', 'equity', 'Opptjent egenkapital', 'balance_sheet'),
('705', 'Udisponert resultat', 'equity', 'Opptjent egenkapital', 'balance_sheet'),
('710', 'Sum opptjent egenkapital', 'equity', 'Opptjent egenkapital', 'balance_sheet'),
('715', 'Sum egenkapital', 'equity', 'Egenkapital', 'balance_sheet'),
('720', 'Pensjonsforpliktelser', 'liability', 'Avsetninger', 'balance_sheet'),
('725', 'Utsatt skatt', 'liability', 'Avsetninger', 'balance_sheet'),
('730', 'Andre avsetning for forpliktelser', 'liability', 'Avsetninger', 'balance_sheet'),
('735', 'Sum avsetning for forpliktelser', 'liability', 'Avsetninger', 'balance_sheet'),
('740', 'Konvertible lån', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('742', 'Ansvarlig lån', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('750', 'Gjeld til kredittinstitusjoner', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('755', 'Langsiktig konserngjeld', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('759', 'Øvrig langsiktig gjeld', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('760', 'Sum annen langsiktig gjeld', 'liability', 'Langsiktig gjeld', 'balance_sheet'),
('765', 'Konvertible lån', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('770', 'Sertifikatlån', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('775', 'Gjeld til kredittinstitusjoner', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('780', 'Leverandørgjeld', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('785', 'Betalbar skatt', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('790', 'Skyldig offentlige avgifter', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('795', 'Utbytte', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('798', 'Konserngjeld', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('800', 'Annen kortsiktig gjeld', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('810', 'Sum kortsiktig gjeld', 'liability', 'Kortsiktig gjeld', 'balance_sheet'),
('820', 'Sum gjeld', 'liability', 'Gjeld', 'balance_sheet'),
('850', 'Sum egenkapital og gjeld', 'equity', 'Egenkapital og gjeld', 'balance_sheet');