-- Populate naeringsspesifikasjon table with NA codes
INSERT INTO public.naeringsspesifikasjon (kode, navn, active) VALUES
('3000', 'Salg og uttak med mva-plikt', true),
('3001', 'Salgsinntekter og uttak av olje', true),
('3002', 'Salgsinntekter og uttak av tørrgass', true),
('3003', 'Salgsinntekter og uttak av våtgass', true),
('3004', 'Tariffinntekt rørledning', true),
('3005', 'Tariffinntekt prosessering', true),
('3006', 'Timer viderefakturert', true),
('3007', 'Annen kostnad viderefakturert', true),
('3008', 'Endring i mer-/mindreuttak av petroleumsprodukter', true),
('3100', 'Salg og uttak med 0 prosent mva.', true),
('3200', 'Salg og uttak utenfor mva-loven', true),
('3300', 'Offentlige særavgifter ved salg', true),
('3400', 'Offentlige tilskudd og refusjoner', true),
('3410', 'Tilskudd kompensasjonsordning', true),
('3500', 'Endring uopptjent inntekt', true),
('3600', 'Inntekt fra utleie av eiendom', true),
('3695', 'Andre leieinntekter', true),
('3700', 'Provisjon', true),
('3710', 'Lisens-, patent- og royalty-inntekter', true),
('3850', 'Verdiendringer av investeringseiendommer etter IFRS', true),
('3870', 'Verdiendringer biologiske eiendeler etter IFRS', true),
('3880', 'Gevinst ved avgang av immaterielle eiendeler og varige driftsmidler', true),
('3885', 'Gevinst ved avgang av finansielle anleggsmidler', true),
('3886', 'Gevinst ved overdragelse av tillatelse til petroleumsvirksomhet', true),
('3900', 'Andre driftsinntekter', true),
('4001', 'Letekostnader', true),
('4002', 'Utbyggingskostnader', true),
('4003', 'Produksjonskostnader', true),
('4004', 'Handling fee / Service fee / Trading fee', true),
('4005', 'Varekostnader inklusiv endring i beholdningen', true),
('4007', 'Endring i mer-/mindreuttak av petroleumsprodukter', true),
('4008', 'Fjernings- og nedstengningskostnader', true),
('4295', 'Endring i beholdningen av ferdige og uferdige egenproduserte varer', true),
('4500', 'Innleid arbeidskraft', true),
('4995', 'Endring i beholdningen av egenproduserte driftsmidler', true),
('5000', 'Lønn og feriepenger med mer', true),
('5300', 'Andre opplysningspliktige godtgjørelser', true),
('5400', 'Arbeidsgiveravgift', true),
('5420', 'Opplysningspliktige pensjonskostnader', true),
('5900', 'Andre personalkostnader', true),
('6000', 'Avskrivning på varige driftsmidler', true),
('6001', 'Avskrivning på produksjonsinnretning og rørledning', true),
('6002', 'Avskrivning på fjernings- og nedstengningseiendeler', true),
('6004', 'Annen avskrivning', true),
('6050', 'Nedskrivning på varige driftsmidler og immaterielle eiendeler', true),
('6051', 'Nedskrivning på produksjonsinnretning og rørledning', true),
('6052', 'Nedskrivning på aktiverte letekostnader', true),
('6053', 'Nedskrivning på anlegg under utførelse', true),
('6054', 'Annen nedskrivning', true),
('6100', 'Frakt- og transportkostnader ved salg', true),
('6110', 'Frakt- og transportkostnad vedrørende salg av olje', true),
('6120', 'Frakt- og transportkostnad vedrørende salg av tørrgass', true),
('6130', 'Frakt- og transportkostnad vedrørende salg av LNG', true),
('6140', 'Frakt- og transportkostnad vedrørende salg av våtgass', true),
('6200', 'Energi og brensel med mer til produksjon', true),
('6300', 'Leie av lokaler', true),
('6340', 'Strøm og oppvarming', true),
('6350', 'IT kostnader', true),
('6395', 'Renovasjon, vann, avløp, renhold med mer', true),
('6400', 'Leie av maskiner, inventar og utstyr med mer', true),
('6440', 'Langtidsleie/leasing av bil', true),
('6500', 'Verktøy, inventar med mer som skal kostnadsføres direkte', true),
('6600', 'Reparasjoner og vedlikehold av bygninger', true),
('6695', 'Reparasjoner og vedlikehold av utstyr med mer', true),
('6700', 'Regnskapstjenester, rådgivning med mer', true),
('6750', 'Konserntjenester', true),
('6751', 'Kostnadsreduksjon timer viderefakturert', true),
('6752', 'Kostnadsreduksjon annen kostnad viderefakturert', true),
('6995', 'Kontorrekvisita, elektronisk kommunikasjon, porto med mer', true),
('7000', 'Drivstoff', true),
('7020', 'Vedlikehold', true),
('7040', 'Forsikring og avgifter', true),
('7080', 'Fradrag for bruk av privat bil i næringsvirksomheten', true),
('7099', 'Privat bruk av næringsbil', true),
('7155', 'Reise-, diett- og bilgodtgjørelser, med opplysningsplikt', true),
('7165', 'Reise- og diettkostnader, uten opplysningsplikt', true),
('7295', 'Provisjonskostnader', true),
('7330', 'Salgs- og reklamekostnader', true),
('7370', 'Representasjonskostnader', true),
('7440', 'Gaver', true),
('7490', 'Kontingenter', true),
('7500', 'Forsikringspremier', true),
('7501', 'Driftsforsikring', true),
('7502', 'Utbyggingsforsikring', true),
('7503', 'Annen forsikring', true),
('7565', 'Garanti- og servicekostnader', true),
('7600', 'Lisenser, patenter og royalties', true),
('7650', 'Forskning og utviklingskostnad', true),
('7651', 'Tilskudd til vitenskapelig forskning mv jf sktl § 6-42', true),
('7700', 'Andre kostnader', true),
('7701', 'Co2-avgift', true),
('7830', 'Tap på fordringer', true),
('7860', 'Tap på kontrakter', true),
('7880', 'Tap ved avgang av immaterielle eiendeler og varige driftsmidler', true),
('7885', 'Tap ved avgang av finansielle anleggsmidler', true),
('7886', 'Tap ved overdragelse av tillatelse til petroleumsvirksomhet', true),
('8005', 'Netto positiv resultatandel vedrørende investering i DS, TS og FKV', true),
('8030', 'Renteinntekt fra foretak i samme konsern', true),
('8050', 'Annen renteinntekt', true),
('8054', 'Garantiinntekter fra foretak i samme konsern', true),
('8059', 'Garantiinntekt', true),
('8060', 'Gevinst ved kursendring på valuta', true),
('8074', 'Gevinst ved realisasjon av aksjer, egenkapitalbevis og fondsandeler', true),
('8075', 'Finansinntekt fra foretak i samme konsern', true),
('8079', 'Andre finansinntekter', true),
('8080', 'Verdiøkning av finansielle instrumenter vurdert til virkelig verdi', true),
('8090', 'Inntekt av andre investeringer/utbytte', true),
('8100', 'Verdireduksjon av finansielle instrumenter vurdert til virkelig verdi', true),
('8105', 'Netto negativ resultatandel vedrørende investering i DS, TS og FKV', true),
('8115', 'Nedskriving av finansielle eiendeler', true),
('8120', 'Kalkulatorisk rente fjernings- og nedstengningsforpliktelse', true),
('8130', 'Rentekostnad til foretak i samme konsern', true),
('8150', 'Annen rentekostnad', true),
('8154', 'Garantikostnad til foretak i samme konsern', true),
('8159', 'Annen garantikostnad', true),
('8160', 'Tap ved kursendring på valuta', true),
('8174', 'Tap ved realisasjon av aksjer, egenkapitalbevis og fondsandeler', true),
('8175', 'Finanskostnader til foretak i samme konsern', true),
('8179', 'Andre finanskostnader', true),
('8300', 'Betalbar skatt på ordinært resultat', true),
('8321', 'Økning i utsatt skatt/nedgang i utsatt skattefordel på ordinært resultat', true),
('8322', 'Nedgang i utsatt skatt/økning i utsatt skattefordel på ordinært resultat', true),
('8323', 'For lite avsatt skatt fra forrige år', true),
('8324', 'For mye avsatt skatt fra forrige år', true),
('1000', 'Utvikling', true),
('1020', 'Varige konsesjoner, patenter, lisenser, rettigheter med mer', true),
('1070', 'Utsatt skattefordel', true),
('1080', 'Goodwill', true),
('1101', 'Aktiverte letekostnader', true),
('1102', 'Felt under utbygging', true),
('1103', 'Produksjonsinnretning og rørledning', true),
('1104', 'Fjernings- og nedstengningseiendeler', true),
('1105', 'Forretningsbygg', true),
('1115', 'Bygg, anlegg, hotell o.l.', true),
('1117', 'Elektroteknisk utrustning i kraftforetak mv.', true),
('1120', 'Fast teknisk installasjon i bygninger', true),
('1130', 'Anlegg og maskiner under bygging', true),
('1150', 'Tomter og andre grunnarealer', true),
('1160', 'Bolig inkl. boligtomter, hytter mv.', true),
('1180', 'Investeringseiendommer', true),
('1205', 'Personbiler, maskiner, inventar', true),
('1221', 'Skip, rigger mv.', true),
('1225', 'Fly, helikopter mv.', true),
('1238', 'Vare- og lastebiler, busser mv.', true),
('1239', 'Varebiler med nullutslipp', true),
('1280', 'Kontormaskiner o.l.', true),
('1290', 'Andre driftsmidler', true),
('1312', 'Investeringer i datter- og konsernselskap med deltakerfastsetting', true),
('1313', 'Investeringer i andre datter- og konsernselskap', true),
('1320', 'Lån til foretak i samme konsern', true),
('1331', 'Investeringer i tilknyttede selskap med deltakerfastsetting', true),
('1332', 'Investeringer i andre tilknyttede selskap', true),
('1340', 'Lån til tilknyttet selskap og felles kontrollert virksomhet', true),
('1350', 'Investeringer i aksjer, andeler og verdipapirfondsandeler', true),
('1360', 'Obligasjoner', true),
('1370', 'Fordringer på personlige eiere, styremedl. o.l.', true),
('1380', 'Krav/fordringer mot ansatte', true),
('1390', 'Andre langsiktige fordringer', true),
('1395', 'Netto pensjonsmidler', true),
('1400', 'Varelager', true),
('1401', 'Beholdning av egenproduserte varer for bruk i egen jordbruksvirksomhet', true),
('1470', 'Mindreuttak av petroleumsprodukter', true),
('1490', 'Biologiske eiendeler', true),
('1500', 'Kundefordringer', true),
('1501', 'Kundefordringer på selskap i samme konsern', true),
('1530', 'Opptjente ikke fakturerte driftsinntekter', true),
('1560', 'Andre fordringer på selskap i samme konsern', true),
('1565', 'Kortsiktige fordringer mot personlig eier, styremedlem o.l.', true),
('1570', 'Andre kortsiktige krav/fordringer', true),
('1780', 'Krav på innbetalt selskapskapital', true),
('1800', 'Ikke-markedsbaserte aksjer og verdipapirfondsandeler', true),
('1810', 'Markedsbaserte aksjer og verdipapirfondsandeler', true),
('1830', 'Markedsbaserte obligasjoner, sertifikater mv.', true),
('1840', 'Andre obligasjoner og sertifikater', true),
('1880', 'Andre finansielle instrumenter', true),
('1895', 'Andel i selskap med deltakerfastsetting', true),
('1900', 'Kontanter', true),
('1920', 'Bankinnskudd', true),
('1950', 'Innskudd på skattetrekkskonto', true),
('2000', 'Aksjekapital/Egenkapital andre foretak', true),
('2010', 'Egne aksjer', true),
('2015', 'Felleseid andelskapital', true),
('2020', 'Overkurs', true),
('2030', 'Annen innskutt egenkapital', true),
('2043', 'Fond for vurderingsforskjeller', true),
('2045', 'Fond for urealiserte gevinster', true),
('2050', 'Positiv egenkapital', true),
('2055', 'Avsatt utbytte - IFRS', true),
('2080', 'Negativ egenkapital', true),
('2100', 'Pensjonsforpliktelser', true),
('2120', 'Utsatt skatt', true),
('2130', 'Derivater', true),
('2160', 'Uopptjent inntekt', true),
('2180', 'Avsetninger for forpliktelser', true),
('2185', 'Avsetninger for fjerning- og nedstengningsforpliktelser', true),
('2200', 'Konvertible lån', true),
('2210', 'Obligasjonslån', true),
('2220', 'Langsiktig gjeld til banker og andre kredittinstitusjoner', true),
('2250', 'Gjeld til ansatte og personlige eiere', true),
('2260', 'Gjeld til selskap i samme konsern', true),
('2280', 'Stille interessentinnskudd og ansvarlig lånekapital', true),
('2290', 'Annen langsiktig gjeld', true),
('2310', 'Konvertible lån', true),
('2320', 'Obligasjonslån', true),
('2330', 'Derivater', true),
('2380', 'Kortsiktig gjeld til banker og andre kredittinstitusjoner', true),
('2400', 'Gjeld til leverandører', true),
('2460', 'Leverandørgjeld til selskap i samme konsern', true),
('2470', 'Meruttak av petroleumsprodukter', true),
('2500', 'Betalbar skatt, ikke fastsatt', true),
('2510', 'Betalbar skatt, fastsatt', true),
('2600', 'Skattetrekk og andre trekk', true),
('2740', 'Skyldig merverdiavgift', true),
('2770', 'Skyldig arbeidsgiveravgift', true),
('2790', 'Andre offentlige avgifter', true),
('2800', 'Avsatt utbytte', true),
('2900', 'Forskudd fra kunder', true),
('2910', 'Gjeld til ansatte og personlige eiere', true),
('2920', 'Gjeld til selskap i samme konsern', true),
('2949', 'Skyldig lønn og feriepenger med mer', true),
('2950', 'Skyldige gjeldsrenter', true),
('2970', 'Uopptjent inntekt', true),
('2980', 'Avsetninger for forpliktelser', true),
('2990', 'Annen kortsiktig gjeld', true);