
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use hardcoded values for Lovable environment as fallback
const SUPABASE_URL = import.meta.env.SUPABASE_URL ?? 
                     import.meta.env.VITE_SUPABASE_URL ?? 
                     'https://fxelhfwaoizqyecikscu.supabase.co';

const SUPABASE_ANON_KEY = import.meta.env.SUPABASE_ANON_KEY ?? 
                          import.meta.env.VITE_SUPABASE_ANON_KEY ?? 
                          'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZWxoZndhb2l6cXllY2lrc2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjM2NzksImV4cCI6MjA2MDczOTY3OX0.h20hURN-5qCAtI8tZaHpEoCnNmfdhIuYJG3tgXyvKqc';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing required Supabase environment variables. Please check your environment configuration.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
